services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fzbird20250615
      MYSQL_DATABASE: gallerydb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - gallery-network

  backend:
    build: ./backend
    pull_policy: always
    container_name: gallery_backend
    restart: always
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - gallery-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - node:18-alpine
        - gallery-frontend:latest
    pull_policy: always
    container_name: gallery_frontend
    restart: always
    ports:
      # 开发/测试端口：http://localhost:3300
      - "3300:80"
      
      # 生产/标准端口：http://localhost (反向代理模式)
      - "80:80"
      
      # 说明：
      # - 3300端口：适合开发和多项目环境，避免端口冲突
      # - 80端口：标准HTTP端口，用户友好，适合生产环境
      # - 两个端口指向同一个nginx容器，提供灵活的访问方式
    depends_on:
      - backend
    networks:
      - gallery-network

volumes:
  mysql_data:

networks:
  gallery-network:
    driver: bridge 