# 生产环境配置 - 只使用80端口，标准HTTP访问
# 使用方法: docker-compose -f docker-compose.prod.yml up -d

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fzbird20250615
      MYSQL_DATABASE: gallerydb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - gallery-network

  backend:
    build: ./backend
    pull_policy: always
    container_name: gallery_backend
    restart: always
    entrypoint: /app/entrypoint.sh
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - gallery-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - node:18-alpine
        - gallery-frontend:latest
    pull_policy: always
    container_name: gallery_frontend
    restart: always
    ports:
      # 生产环境使用标准HTTP端口
      - "80:80"
    depends_on:
      - backend
    networks:
      - gallery-network

volumes:
  mysql_data:

networks:
  gallery-network:
    driver: bridge 