# 开发环境配置 - 只使用3300端口，避免端口冲突
# 使用方法: 
#   1. 先启动共享MySQL: docker-compose -f docker-compose.mysql.yml up -d
#   2. 再启动开发环境: docker-compose -f docker-compose.dev.yml up -d

services:
  backend:
    build: ./backend
    pull_policy: always
    container_name: gallery_backend
    restart: always
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      # 数据库连接配置 - 连接到共享MySQL容器
      - DATABASE_URL=mysql+pymysql://root:fzbird20250615@mysql_db:3306/gallery_db
    networks:
      - gallery-network
      - shared-mysql-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - node:18-alpine
        - gallery-frontend:latest
    pull_policy: always
    container_name: gallery_frontend
    restart: always
    ports:
      # 开发环境只使用3300端口
      - "3300:80"
    depends_on:
      - backend
    networks:
      - gallery-network

networks:
  gallery-network:
    driver: bridge
  shared-mysql-network:
    external: true