"""add is_published to gallery

Revision ID: 15332ef20667
Revises: 48e5cfbd4e2c
Create Date: 2025-06-28 14:58:06.882100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '15332ef20667'
down_revision: Union[str, None] = '48e5cfbd4e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galleries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('cover_image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cover_image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galleries_title'), 'galleries', ['title'], unique=False)
    op.drop_table('gallery')
    op.drop_constraint(op.f('image_ibfk_1'), 'image', type_='foreignkey')
    op.create_foreign_key(None, 'image', 'galleries', ['gallery_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.create_foreign_key(op.f('image_ibfk_1'), 'image', 'gallery', ['gallery_id'], ['id'])
    op.create_table('gallery',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cover_image_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cover_image_id'], ['image.id'], name=op.f('gallery_ibfk_2')),
    sa.ForeignKeyConstraint(['id'], ['content.id'], name=op.f('gallery_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_galleries_title'), table_name='galleries')
    op.drop_table('galleries')
    # ### end Alembic commands ###
