"""change_topic_cover_image_url_to_cover_image_id

Revision ID: bff166b91aba
Revises: c441d2552c94
Create Date: 2025-06-23 00:44:16.678113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bff166b91aba'
down_revision: Union[str, None] = 'c441d2552c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('cover_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topic', 'image', ['cover_image_id'], ['id'])
    op.drop_column('topic', 'cover_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('cover_image_url', mysql.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.drop_column('topic', 'cover_image_id')
    # ### end Alembic commands ###
