"""add_simplified_topic_table_with_topic_id_in_content

Revision ID: c441d2552c94
Revises: 261483e762bf
Create Date: 2025-06-22 22:36:24.832466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c441d2552c94'
down_revision: Union[str, None] = '261483e762bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_galleries')
    op.add_column('content', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'content', 'topic', ['topic_id'], ['id'])
    op.drop_constraint(op.f('topic_ibfk_1'), 'topic', type_='foreignkey')
    op.drop_column('topic', 'views_count')
    op.drop_column('topic', 'galleries_count')
    op.drop_column('topic', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('creator_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('topic', sa.Column('galleries_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('topic', sa.Column('views_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('topic_ibfk_1'), 'topic', 'user', ['creator_id'], ['id'])
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_column('content', 'topic_id')
    op.create_table('topic_galleries',
    sa.Column('topic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gallery_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], name=op.f('topic_galleries_ibfk_1')),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name=op.f('topic_galleries_ibfk_2')),
    sa.PrimaryKeyConstraint('topic_id', 'gallery_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
